# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmAlterarFornecedores.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlterarForncedores(object):
    def setupUi(self, AlterarForncedores):
        AlterarForncedores.setObjectName("AlterarForncedores")
        AlterarForncedores.resize(391, 299)
        AlterarForncedores.setMinimumSize(QtCore.QSize(391, 299))
        AlterarForncedores.setMaximumSize(QtCore.QSize(391, 299))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imagens/P em png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AlterarForncedores.setWindowIcon(icon)
        AlterarForncedores.setStyleSheet("background-color: white;")
        AlterarForncedores.setIconSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(AlterarForncedores)
        self.centralwidget.setObjectName("centralwidget")
        self.line_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.line_nome.setGeometry(QtCore.QRect(20, 20, 351, 51))
        self.line_nome.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_nome.setObjectName("line_nome")
        self.btn_alterar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_alterar.setGeometry(QtCore.QRect(20, 240, 351, 41))
        self.btn_alterar.setMinimumSize(QtCore.QSize(351, 41))
        self.btn_alterar.setMaximumSize(QtCore.QSize(351, 16777215))
        self.btn_alterar.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_alterar.setObjectName("btn_alterar")
        self.line_endereco = QtWidgets.QLineEdit(self.centralwidget)
        self.line_endereco.setGeometry(QtCore.QRect(20, 90, 351, 51))
        self.line_endereco.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_endereco.setObjectName("line_endereco")
        self.line_contato = QtWidgets.QLineEdit(self.centralwidget)
        self.line_contato.setGeometry(QtCore.QRect(20, 160, 351, 51))
        self.line_contato.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_contato.setObjectName("line_contato")
        AlterarForncedores.setCentralWidget(self.centralwidget)

        self.retranslateUi(AlterarForncedores)
        QtCore.QMetaObject.connectSlotsByName(AlterarForncedores)

    def retranslateUi(self, AlterarForncedores):
        _translate = QtCore.QCoreApplication.translate
        AlterarForncedores.setWindowTitle(_translate("AlterarForncedores", "Alterar Fornecedores"))
        self.line_nome.setPlaceholderText(_translate("AlterarForncedores", "Nome"))
        self.btn_alterar.setText(_translate("AlterarForncedores", "Finalizar Alterações"))
        self.line_endereco.setPlaceholderText(_translate("AlterarForncedores", "Endereço"))
        self.line_contato.setPlaceholderText(_translate("AlterarForncedores", "(00) 0 0000-0000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AlterarForncedores = QtWidgets.QMainWindow()
    ui = Ui_AlterarForncedores()
    ui.setupUi(AlterarForncedores)
    AlterarForncedores.show()
    sys.exit(app.exec_())
