# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmColaborador.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmColaborador(object):
    def setupUi(self, FrmAdmin):
        FrmAdmin.setObjectName("FrmAdmin")
        FrmAdmin.resize(1091, 611)
        FrmAdmin.setMinimumSize(QtCore.QSize(1091, 611))
        FrmAdmin.setMaximumSize(QtCore.QSize(1091, 611))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imagens/P em png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrmAdmin.setWindowIcon(icon)
        FrmAdmin.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(FrmAdmin)
        self.centralwidget.setObjectName("centralwidget")
        self.TelasPrincipais = QtWidgets.QStackedWidget(self.centralwidget)
        self.TelasPrincipais.setGeometry(QtCore.QRect(0, 0, 1091, 611))
        self.TelasPrincipais.setMinimumSize(QtCore.QSize(1091, 611))
        self.TelasPrincipais.setMaximumSize(QtCore.QSize(1091, 611))
        self.TelasPrincipais.setObjectName("TelasPrincipais")
        self.Admin = QtWidgets.QWidget()
        self.Admin.setObjectName("Admin")
        self.bara_menu_esquerda = QtWidgets.QFrame(self.Admin)
        self.bara_menu_esquerda.setGeometry(QtCore.QRect(0, 0, 61, 611))
        self.bara_menu_esquerda.setStyleSheet("background-color: rgb(159, 63, 250);")
        self.bara_menu_esquerda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bara_menu_esquerda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bara_menu_esquerda.setObjectName("bara_menu_esquerda")
        self.btn_home = QtWidgets.QPushButton(self.bara_menu_esquerda)
        self.btn_home.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.btn_home.setStyleSheet("QPushButton {\n"
"border: solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: solid;\n"
"    background-color: rgb(159, 103, 250);\n"
"}")
        self.btn_home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icones/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon1)
        self.btn_home.setIconSize(QtCore.QSize(30, 30))
        self.btn_home.setObjectName("btn_home")
        self.btn_configs = QtWidgets.QPushButton(self.bara_menu_esquerda)
        self.btn_configs.setGeometry(QtCore.QRect(0, 560, 61, 51))
        self.btn_configs.setStyleSheet("QPushButton {\n"
"border: solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: solid;\n"
"    background-color: rgb(159, 103, 250);\n"
"}")
        self.btn_configs.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icones/engrenagem_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_configs.setIcon(icon2)
        self.btn_configs.setIconSize(QtCore.QSize(30, 30))
        self.btn_configs.setObjectName("btn_configs")
        self.btn_fornecedores = QtWidgets.QPushButton(self.bara_menu_esquerda)
        self.btn_fornecedores.setGeometry(QtCore.QRect(0, 50, 61, 51))
        self.btn_fornecedores.setStyleSheet("QPushButton {\n"
"border: solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: solid;\n"
"    background-color: rgb(159, 103, 250);\n"
"}")
        self.btn_fornecedores.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icones/pedidos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_fornecedores.setIcon(icon3)
        self.btn_fornecedores.setIconSize(QtCore.QSize(50, 40))
        self.btn_fornecedores.setObjectName("btn_fornecedores")
        self.btn_vendas = QtWidgets.QPushButton(self.bara_menu_esquerda)
        self.btn_vendas.setGeometry(QtCore.QRect(0, 100, 61, 51))
        self.btn_vendas.setStyleSheet("QPushButton {\n"
"border: solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: solid;\n"
"    background-color: rgb(159, 103, 250);\n"
"}")
        self.btn_vendas.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icones/pedidos2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_vendas.setIcon(icon4)
        self.btn_vendas.setIconSize(QtCore.QSize(65, 40))
        self.btn_vendas.setObjectName("btn_vendas")
        self.btn_produtos = QtWidgets.QPushButton(self.bara_menu_esquerda)
        self.btn_produtos.setGeometry(QtCore.QRect(0, 150, 61, 51))
        self.btn_produtos.setStyleSheet("QPushButton {\n"
"border: solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: solid;\n"
"    background-color: rgb(159, 103, 250);\n"
"}")
        self.btn_produtos.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Imagens/btn_produtos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_produtos.setIcon(icon5)
        self.btn_produtos.setIconSize(QtCore.QSize(60, 45))
        self.btn_produtos.setObjectName("btn_produtos")
        self.barra_menu_topo = QtWidgets.QFrame(self.Admin)
        self.barra_menu_topo.setGeometry(QtCore.QRect(60, 0, 1041, 51))
        self.barra_menu_topo.setStyleSheet("background-color: rgb(159, 63, 250);")
        self.barra_menu_topo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barra_menu_topo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barra_menu_topo.setObjectName("barra_menu_topo")
        self.btn_voltar = QtWidgets.QPushButton(self.barra_menu_topo)
        self.btn_voltar.setGeometry(QtCore.QRect(970, 0, 61, 51))
        self.btn_voltar.setStyleSheet("QPushButton {\n"
"border: solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: solid;\n"
"    background-color: rgb(159, 103, 250);\n"
"}")
        self.btn_voltar.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icones/sair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_voltar.setIcon(icon6)
        self.btn_voltar.setIconSize(QtCore.QSize(70, 200))
        self.btn_voltar.setObjectName("btn_voltar")
        self.lbl_seja_bem_vindo = QtWidgets.QLabel(self.barra_menu_topo)
        self.lbl_seja_bem_vindo.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.lbl_seja_bem_vindo.setStyleSheet("color: white;\n"
"font: 12pt \"Montserrat\";")
        self.lbl_seja_bem_vindo.setObjectName("lbl_seja_bem_vindo")
        self.Telas_do_menu = QtWidgets.QStackedWidget(self.Admin)
        self.Telas_do_menu.setGeometry(QtCore.QRect(60, 50, 1031, 561))
        self.Telas_do_menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Telas_do_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Telas_do_menu.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Telas_do_menu.setObjectName("Telas_do_menu")
        self.pg_home = QtWidgets.QWidget()
        self.pg_home.setObjectName("pg_home")
        self.label = QtWidgets.QLabel(self.pg_home)
        self.label.setGeometry(QtCore.QRect(260, 30, 481, 461))
        self.label.setStyleSheet("background-image: url(:/icones/logo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.funcoes = QtWidgets.QStackedWidget(self.pg_home)
        self.funcoes.setGeometry(QtCore.QRect(0, 0, 1031, 561))
        self.funcoes.setObjectName("funcoes")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.quadro_noticias = QtWidgets.QFrame(self.home)
        self.quadro_noticias.setGeometry(QtCore.QRect(560, 40, 441, 481))
        self.quadro_noticias.setStyleSheet("background-color: #9f3ffa;\n"
"border-radius: 5px;")
        self.quadro_noticias.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quadro_noticias.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quadro_noticias.setObjectName("quadro_noticias")
        self.lbl_titulo = QtWidgets.QLabel(self.quadro_noticias)
        self.lbl_titulo.setGeometry(QtCore.QRect(110, 30, 221, 41))
        self.lbl_titulo.setStyleSheet("color: white;\n"
"font: 20pt \"Montserrat\";")
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_noticia3 = QtWidgets.QLabel(self.quadro_noticias)
        self.lbl_noticia3.setGeometry(QtCore.QRect(90, 240, 341, 51))
        self.lbl_noticia3.setStyleSheet("color: white;\n"
"font: 10pt \"Montserrat\";")
        self.lbl_noticia3.setObjectName("lbl_noticia3")
        self.lbl_imagem3 = QtWidgets.QLabel(self.quadro_noticias)
        self.lbl_imagem3.setGeometry(QtCore.QRect(15, 240, 61, 61))
        self.lbl_imagem3.setStyleSheet("")
        self.lbl_imagem3.setText("")
        self.lbl_imagem3.setPixmap(QtGui.QPixmap(":/icones/sugestões.png"))
        self.lbl_imagem3.setScaledContents(True)
        self.lbl_imagem3.setObjectName("lbl_imagem3")
        self.lbl_imagem2 = QtWidgets.QLabel(self.quadro_noticias)
        self.lbl_imagem2.setGeometry(QtCore.QRect(10, 160, 71, 71))
        self.lbl_imagem2.setStyleSheet("")
        self.lbl_imagem2.setText("")
        self.lbl_imagem2.setPixmap(QtGui.QPixmap(":/icones/ambiente.png"))
        self.lbl_imagem2.setScaledContents(True)
        self.lbl_imagem2.setObjectName("lbl_imagem2")
        self.lbl_noticia1 = QtWidgets.QLabel(self.quadro_noticias)
        self.lbl_noticia1.setGeometry(QtCore.QRect(90, 100, 341, 51))
        self.lbl_noticia1.setStyleSheet("color: white;\n"
"font: 10pt \"Montserrat\";")
        self.lbl_noticia1.setObjectName("lbl_noticia1")
        self.lbl_imagem1 = QtWidgets.QLabel(self.quadro_noticias)
        self.lbl_imagem1.setGeometry(QtCore.QRect(10, 90, 71, 71))
        self.lbl_imagem1.setStyleSheet("")
        self.lbl_imagem1.setText("")
        self.lbl_imagem1.setPixmap(QtGui.QPixmap(":/icones/onibus.png"))
        self.lbl_imagem1.setScaledContents(True)
        self.lbl_imagem1.setObjectName("lbl_imagem1")
        self.lbl_noticia2 = QtWidgets.QLabel(self.quadro_noticias)
        self.lbl_noticia2.setGeometry(QtCore.QRect(90, 170, 341, 51))
        self.lbl_noticia2.setStyleSheet("color: white;\n"
"font: 10pt \"Montserrat\";")
        self.lbl_noticia2.setObjectName("lbl_noticia2")
        self.lbl_logo = QtWidgets.QLabel(self.quadro_noticias)
        self.lbl_logo.setGeometry(QtCore.QRect(70, 230, 311, 311))
        self.lbl_logo.setStyleSheet("")
        self.lbl_logo.setText("")
        self.lbl_logo.setPixmap(QtGui.QPixmap(":/icones/logo_branco.png"))
        self.lbl_logo.setScaledContents(True)
        self.lbl_logo.setObjectName("lbl_logo")
        self.lbl_titulo.raise_()
        self.lbl_imagem2.raise_()
        self.lbl_noticia1.raise_()
        self.lbl_imagem1.raise_()
        self.lbl_noticia2.raise_()
        self.lbl_logo.raise_()
        self.lbl_noticia3.raise_()
        self.lbl_imagem3.raise_()
        self.label_3 = QtWidgets.QLabel(self.home)
        self.label_3.setGeometry(QtCore.QRect(40, 200, 481, 131))
        self.label_3.setStyleSheet("color: #9f3ffa;\n"
"font: 28pt \"Montserrat\";")
        self.label_3.setObjectName("label_3")
        self.funcoes.addWidget(self.home)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.funcoes.addWidget(self.page_4)
        self.Telas_do_menu.addWidget(self.pg_home)
        self.pg_fornecedores = QtWidgets.QWidget()
        self.pg_fornecedores.setObjectName("pg_fornecedores")
        self.lbl_titulo_fornecedores = QtWidgets.QLabel(self.pg_fornecedores)
        self.lbl_titulo_fornecedores.setGeometry(QtCore.QRect(340, 30, 371, 20))
        self.lbl_titulo_fornecedores.setStyleSheet("color: #9f3ffa;\n"
"font: 20pt \"Montserrat\";")
        self.lbl_titulo_fornecedores.setObjectName("lbl_titulo_fornecedores")
        self.btn_editar_fornecedores = QtWidgets.QPushButton(self.pg_fornecedores)
        self.btn_editar_fornecedores.setGeometry(QtCore.QRect(430, 500, 161, 41))
        self.btn_editar_fornecedores.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_editar_fornecedores.setObjectName("btn_editar_fornecedores")
        self.btn_excluir_fornecedores = QtWidgets.QPushButton(self.pg_fornecedores)
        self.btn_excluir_fornecedores.setGeometry(QtCore.QRect(630, 500, 161, 41))
        self.btn_excluir_fornecedores.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 17, 49);\n"
"}\n"
"")
        self.btn_excluir_fornecedores.setObjectName("btn_excluir_fornecedores")
        self.tabela_fornecedores = QtWidgets.QTableWidget(self.pg_fornecedores)
        self.tabela_fornecedores.setGeometry(QtCore.QRect(20, 80, 991, 401))
        self.tabela_fornecedores.setStyleSheet("QTableWidget {\n"
"    gridline-color: #9f3ffa;;\n"
"    background-color: transparent;\n"
"    outline: 0;\n"
"    border: 1px solid #9f3ffa;\n"
"    border-top: 0px\n"
"    \n"
"}\n"
"\n"
"QTableWidget::item:selected{\n"
"    background-color:#9f3ffa;;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: #9f3ffa;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid #9f3ffa;\n"
"    background-color: transparent;\n"
"    border-left: 0px;\n"
"    color: black;\n"
"\n"
"}\n"
"")
        self.tabela_fornecedores.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabela_fornecedores.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tabela_fornecedores.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tabela_fornecedores.setTabKeyNavigation(True)
        self.tabela_fornecedores.setProperty("showDropIndicator", False)
        self.tabela_fornecedores.setAlternatingRowColors(False)
        self.tabela_fornecedores.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tabela_fornecedores.setGridStyle(QtCore.Qt.SolidLine)
        self.tabela_fornecedores.setObjectName("tabela_fornecedores")
        self.tabela_fornecedores.setColumnCount(3)
        self.tabela_fornecedores.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_fornecedores.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_fornecedores.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_fornecedores.setHorizontalHeaderItem(2, item)
        self.tabela_fornecedores.verticalHeader().setVisible(False)
        self.tabela_fornecedores.verticalHeader().setSortIndicatorShown(False)
        self.tabela_fornecedores.verticalHeader().setStretchLastSection(False)
        self.btn_adicionar_forncedores = QtWidgets.QPushButton(self.pg_fornecedores)
        self.btn_adicionar_forncedores.setGeometry(QtCore.QRect(230, 500, 161, 41))
        self.btn_adicionar_forncedores.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_adicionar_forncedores.setObjectName("btn_adicionar_forncedores")
        self.Telas_do_menu.addWidget(self.pg_fornecedores)
        self.pg_colaboradores = QtWidgets.QWidget()
        self.pg_colaboradores.setObjectName("pg_colaboradores")
        self.lbl_titulo_colaboradores = QtWidgets.QLabel(self.pg_colaboradores)
        self.lbl_titulo_colaboradores.setGeometry(QtCore.QRect(250, 40, 551, 41))
        self.lbl_titulo_colaboradores.setStyleSheet("font: 30pt \"Montserrat\";\n"
"color: #9f3ffa;\n"
"")
        self.lbl_titulo_colaboradores.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_titulo_colaboradores.setWordWrap(False)
        self.lbl_titulo_colaboradores.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.lbl_titulo_colaboradores.setObjectName("lbl_titulo_colaboradores")
        self.radio_admin = QtWidgets.QRadioButton(self.pg_colaboradores)
        self.radio_admin.setGeometry(QtCore.QRect(750, 368, 82, 17))
        self.radio_admin.setStyleSheet("outline: 0;")
        self.radio_admin.setObjectName("radio_admin")
        self.radio_colaborador = QtWidgets.QRadioButton(self.pg_colaboradores)
        self.radio_colaborador.setGeometry(QtCore.QRect(640, 368, 82, 17))
        self.radio_colaborador.setStyleSheet("outline: 0;")
        self.radio_colaborador.setObjectName("radio_colaborador")
        self.line_nome = QtWidgets.QLineEdit(self.pg_colaboradores)
        self.line_nome.setGeometry(QtCore.QRect(640, 160, 271, 51))
        self.line_nome.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_nome.setObjectName("line_nome")
        self.line_login = QtWidgets.QLineEdit(self.pg_colaboradores)
        self.line_login.setGeometry(QtCore.QRect(640, 230, 271, 51))
        self.line_login.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_login.setText("")
        self.line_login.setObjectName("line_login")
        self.line_senha = QtWidgets.QLineEdit(self.pg_colaboradores)
        self.line_senha.setGeometry(QtCore.QRect(640, 300, 271, 51))
        self.line_senha.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_senha.setObjectName("line_senha")
        self.btn_cadastro = QtWidgets.QPushButton(self.pg_colaboradores)
        self.btn_cadastro.setGeometry(QtCore.QRect(640, 400, 271, 41))
        self.btn_cadastro.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_cadastro.setObjectName("btn_cadastro")
        self.label_5 = QtWidgets.QLabel(self.pg_colaboradores)
        self.label_5.setGeometry(QtCore.QRect(50, 110, 531, 401))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icones/undraw_secure_login_pdn4.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.btn_ver_senha = QtWidgets.QPushButton(self.pg_colaboradores)
        self.btn_ver_senha.setGeometry(QtCore.QRect(920, 336, 30, 31))
        self.btn_ver_senha.setStyleSheet("QPushButton {\n"
"    background-image: url(:/icones/ver senha.png);\n"
"    border: 0px;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-image: url(:/icones/ver senha hover.png);\n"
"}")
        self.btn_ver_senha.setText("")
        self.btn_ver_senha.setObjectName("btn_ver_senha")
        self.label_5.raise_()
        self.lbl_titulo_colaboradores.raise_()
        self.radio_admin.raise_()
        self.radio_colaborador.raise_()
        self.line_nome.raise_()
        self.line_login.raise_()
        self.line_senha.raise_()
        self.btn_cadastro.raise_()
        self.btn_ver_senha.raise_()
        self.Telas_do_menu.addWidget(self.pg_colaboradores)
        self.pg_vendas = QtWidgets.QWidget()
        self.pg_vendas.setObjectName("pg_vendas")
        self.lbl_titulo_usuario_vendas = QtWidgets.QLabel(self.pg_vendas)
        self.lbl_titulo_usuario_vendas.setGeometry(QtCore.QRect(20, 20, 551, 41))
        self.lbl_titulo_usuario_vendas.setStyleSheet("font: 16pt \"Montserrat\";\n"
"color: #9f3ffa;\n"
"")
        self.lbl_titulo_usuario_vendas.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_titulo_usuario_vendas.setWordWrap(False)
        self.lbl_titulo_usuario_vendas.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.lbl_titulo_usuario_vendas.setObjectName("lbl_titulo_usuario_vendas")
        self.line_cliente = QtWidgets.QLineEdit(self.pg_vendas)
        self.line_cliente.setGeometry(QtCore.QRect(380, 90, 161, 31))
        self.line_cliente.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_cliente.setClearButtonEnabled(True)
        self.line_cliente.setObjectName("line_cliente")
        self.tabela_vendas = QtWidgets.QTableWidget(self.pg_vendas)
        self.tabela_vendas.setGeometry(QtCore.QRect(20, 190, 791, 351))
        self.tabela_vendas.setStyleSheet("QTableWidget {\n"
"    gridline-color: #9f3ffa;;\n"
"    background-color: transparent;\n"
"    outline: 0;\n"
"    border: 1px solid #9f3ffa;\n"
"    border-top: 0px\n"
"    \n"
"}\n"
"\n"
"QTableWidget::item:selected{\n"
"    background-color:#9f3ffa;;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: #9f3ffa;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid #9f3ffa;\n"
"    background-color: transparent;\n"
"    border-left: 0px;\n"
"    color: black;\n"
"\n"
"}\n"
"")
        self.tabela_vendas.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabela_vendas.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tabela_vendas.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tabela_vendas.setTabKeyNavigation(True)
        self.tabela_vendas.setProperty("showDropIndicator", False)
        self.tabela_vendas.setAlternatingRowColors(False)
        self.tabela_vendas.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tabela_vendas.setGridStyle(QtCore.Qt.SolidLine)
        self.tabela_vendas.setObjectName("tabela_vendas")
        self.tabela_vendas.setColumnCount(6)
        self.tabela_vendas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_vendas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_vendas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_vendas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_vendas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_vendas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_vendas.setHorizontalHeaderItem(5, item)
        self.tabela_vendas.verticalHeader().setVisible(False)
        self.tabela_vendas.verticalHeader().setSortIndicatorShown(False)
        self.tabela_vendas.verticalHeader().setStretchLastSection(False)
        self.line_codigo_vendas = QtWidgets.QLineEdit(self.pg_vendas)
        self.line_codigo_vendas.setGeometry(QtCore.QRect(20, 140, 161, 31))
        self.line_codigo_vendas.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_codigo_vendas.setClearButtonEnabled(True)
        self.line_codigo_vendas.setObjectName("line_codigo_vendas")
        self.line_quantidade_vendas = QtWidgets.QLineEdit(self.pg_vendas)
        self.line_quantidade_vendas.setGeometry(QtCore.QRect(200, 140, 161, 31))
        self.line_quantidade_vendas.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_quantidade_vendas.setClearButtonEnabled(True)
        self.line_quantidade_vendas.setObjectName("line_quantidade_vendas")
        self.btn_pesquisar = QtWidgets.QPushButton(self.pg_vendas)
        self.btn_pesquisar.setGeometry(QtCore.QRect(20, 80, 51, 41))
        self.btn_pesquisar.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_pesquisar.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Imagens/lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pesquisar.setIcon(icon7)
        self.btn_pesquisar.setIconSize(QtCore.QSize(25, 25))
        self.btn_pesquisar.setObjectName("btn_pesquisar")
        self.line_search_bar = QtWidgets.QLineEdit(self.pg_vendas)
        self.line_search_bar.setGeometry(QtCore.QRect(70, 80, 291, 41))
        self.line_search_bar.setStyleSheet("border: 2px solid #9f3ffa;\n"
"font: 10pt \"Montserrat\";")
        self.line_search_bar.setCursorPosition(0)
        self.line_search_bar.setClearButtonEnabled(True)
        self.line_search_bar.setObjectName("line_search_bar")
        self.lbl_total_venda = QtWidgets.QLabel(self.pg_vendas)
        self.lbl_total_venda.setGeometry(QtCore.QRect(680, 80, 251, 41))
        self.lbl_total_venda.setStyleSheet("font: 18pt \"Montserrat\";\n"
"color: #9f3ffa;\n"
"")
        self.lbl_total_venda.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_total_venda.setWordWrap(False)
        self.lbl_total_venda.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.lbl_total_venda.setObjectName("lbl_total_venda")
        self.lbl_total_valor = QtWidgets.QLabel(self.pg_vendas)
        self.lbl_total_valor.setGeometry(QtCore.QRect(920, 80, 131, 41))
        self.lbl_total_valor.setStyleSheet("font: 18pt \"Montserrat\";\n"
"color: #9f3ffa;\n"
"")
        self.lbl_total_valor.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_total_valor.setWordWrap(False)
        self.lbl_total_valor.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.lbl_total_valor.setObjectName("lbl_total_valor")
        self.line_desconto_vendas = QtWidgets.QLineEdit(self.pg_vendas)
        self.line_desconto_vendas.setGeometry(QtCore.QRect(380, 140, 161, 31))
        self.line_desconto_vendas.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_desconto_vendas.setClearButtonEnabled(True)
        self.line_desconto_vendas.setObjectName("line_desconto_vendas")
        self.btn_adicionar_compra = QtWidgets.QPushButton(self.pg_vendas)
        self.btn_adicionar_compra.setGeometry(QtCore.QRect(560, 140, 101, 31))
        self.btn_adicionar_compra.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_adicionar_compra.setObjectName("btn_adicionar_compra")
        self.btn_excluir_item = QtWidgets.QPushButton(self.pg_vendas)
        self.btn_excluir_item.setGeometry(QtCore.QRect(830, 400, 181, 41))
        self.btn_excluir_item.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 17, 49);\n"
"}\n"
"")
        self.btn_excluir_item.setObjectName("btn_excluir_item")
        self.btn_finalizar_compra = QtWidgets.QPushButton(self.pg_vendas)
        self.btn_finalizar_compra.setGeometry(QtCore.QRect(830, 280, 181, 41))
        self.btn_finalizar_compra.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_finalizar_compra.setObjectName("btn_finalizar_compra")
        self.btn_confirmar_cliente = QtWidgets.QPushButton(self.pg_vendas)
        self.btn_confirmar_cliente.setGeometry(QtCore.QRect(560, 90, 101, 31))
        self.btn_confirmar_cliente.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_confirmar_cliente.setObjectName("btn_confirmar_cliente")
        self.btn_pagamento = QtWidgets.QPushButton(self.pg_vendas)
        self.btn_pagamento.setGeometry(QtCore.QRect(830, 340, 181, 41))
        self.btn_pagamento.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_pagamento.setObjectName("btn_pagamento")
        self.lbl_hora_data = QtWidgets.QLabel(self.pg_vendas)
        self.lbl_hora_data.setGeometry(QtCore.QRect(830, 520, 181, 21))
        self.lbl_hora_data.setStyleSheet("font: 13pt \"Montserrat\";\n"
"color: #9f3ffa;\n"
"")
        self.lbl_hora_data.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_hora_data.setWordWrap(False)
        self.lbl_hora_data.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.lbl_hora_data.setObjectName("lbl_hora_data")
        self.Telas_do_menu.addWidget(self.pg_vendas)
        self.pg_produtos = QtWidgets.QWidget()
        self.pg_produtos.setObjectName("pg_produtos")
        self.lbl_titulo_produtos = QtWidgets.QLabel(self.pg_produtos)
        self.lbl_titulo_produtos.setGeometry(QtCore.QRect(20, 20, 241, 41))
        self.lbl_titulo_produtos.setStyleSheet("font: 16pt \"Montserrat\";\n"
"color: #9f3ffa;\n"
"")
        self.lbl_titulo_produtos.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_titulo_produtos.setWordWrap(False)
        self.lbl_titulo_produtos.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.lbl_titulo_produtos.setObjectName("lbl_titulo_produtos")
        self.tabela_produto = QtWidgets.QTableWidget(self.pg_produtos)
        self.tabela_produto.setGeometry(QtCore.QRect(20, 190, 791, 351))
        self.tabela_produto.setStyleSheet("QTableWidget {\n"
"    gridline-color: #9f3ffa;;\n"
"    background-color: transparent;\n"
"    outline: 0;\n"
"    border: 1px solid #9f3ffa;\n"
"    border-top: 0px\n"
"    \n"
"}\n"
"\n"
"QTableWidget::item:selected{\n"
"    background-color:#9f3ffa;;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: #9f3ffa;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid #9f3ffa;\n"
"    background-color: transparent;\n"
"    border-left: 0px;\n"
"    color: black;\n"
"\n"
"}\n"
"")
        self.tabela_produto.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabela_produto.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tabela_produto.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tabela_produto.setTabKeyNavigation(True)
        self.tabela_produto.setProperty("showDropIndicator", False)
        self.tabela_produto.setAlternatingRowColors(False)
        self.tabela_produto.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tabela_produto.setGridStyle(QtCore.Qt.SolidLine)
        self.tabela_produto.setObjectName("tabela_produto")
        self.tabela_produto.setColumnCount(6)
        self.tabela_produto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_produto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_produto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_produto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_produto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_produto.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_produto.setHorizontalHeaderItem(5, item)
        self.tabela_produto.verticalHeader().setVisible(False)
        self.tabela_produto.verticalHeader().setSortIndicatorShown(False)
        self.tabela_produto.verticalHeader().setStretchLastSection(False)
        self.btn_cadastrar_produto = QtWidgets.QPushButton(self.pg_produtos)
        self.btn_cadastrar_produto.setGeometry(QtCore.QRect(830, 270, 181, 41))
        self.btn_cadastrar_produto.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_cadastrar_produto.setObjectName("btn_cadastrar_produto")
        self.btn_alterar_produto = QtWidgets.QPushButton(self.pg_produtos)
        self.btn_alterar_produto.setGeometry(QtCore.QRect(830, 330, 181, 41))
        self.btn_alterar_produto.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_alterar_produto.setObjectName("btn_alterar_produto")
        self.btn_excluir_produto = QtWidgets.QPushButton(self.pg_produtos)
        self.btn_excluir_produto.setGeometry(QtCore.QRect(830, 390, 181, 41))
        self.btn_excluir_produto.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_excluir_produto.setObjectName("btn_excluir_produto")
        self.line_search_Bar = QtWidgets.QLineEdit(self.pg_produtos)
        self.line_search_Bar.setGeometry(QtCore.QRect(70, 80, 291, 41))
        self.line_search_Bar.setStyleSheet("border: 2px solid #9f3ffa;\n"
"font: 10pt \"Montserrat\";")
        self.line_search_Bar.setCursorPosition(0)
        self.line_search_Bar.setClearButtonEnabled(True)
        self.line_search_Bar.setObjectName("line_search_Bar")
        self.btn_pesquisar_produto = QtWidgets.QPushButton(self.pg_produtos)
        self.btn_pesquisar_produto.setGeometry(QtCore.QRect(20, 80, 51, 41))
        self.btn_pesquisar_produto.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_pesquisar_produto.setText("")
        self.btn_pesquisar_produto.setIcon(icon7)
        self.btn_pesquisar_produto.setIconSize(QtCore.QSize(25, 25))
        self.btn_pesquisar_produto.setObjectName("btn_pesquisar_produto")
        self.line_codigo_produto = QtWidgets.QLineEdit(self.pg_produtos)
        self.line_codigo_produto.setGeometry(QtCore.QRect(20, 140, 161, 31))
        self.line_codigo_produto.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_codigo_produto.setClearButtonEnabled(True)
        self.line_codigo_produto.setObjectName("line_codigo_produto")
        self.btn_confirmar_codigo = QtWidgets.QPushButton(self.pg_produtos)
        self.btn_confirmar_codigo.setGeometry(QtCore.QRect(200, 140, 101, 31))
        self.btn_confirmar_codigo.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_confirmar_codigo.setObjectName("btn_confirmar_codigo")
        self.lbl_hora_data_produtos = QtWidgets.QLabel(self.pg_produtos)
        self.lbl_hora_data_produtos.setGeometry(QtCore.QRect(830, 520, 181, 21))
        self.lbl_hora_data_produtos.setStyleSheet("font: 13pt \"Montserrat\";\n"
"color: #9f3ffa;\n"
"")
        self.lbl_hora_data_produtos.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_hora_data_produtos.setWordWrap(False)
        self.lbl_hora_data_produtos.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.lbl_hora_data_produtos.setObjectName("lbl_hora_data_produtos")
        self.Telas_do_menu.addWidget(self.pg_produtos)
        self.pg_cadastar_produtos = QtWidgets.QWidget()
        self.pg_cadastar_produtos.setObjectName("pg_cadastar_produtos")
        self.lbl_titulo_cadastrar_produto = QtWidgets.QLabel(self.pg_cadastar_produtos)
        self.lbl_titulo_cadastrar_produto.setGeometry(QtCore.QRect(20, 30, 241, 41))
        self.lbl_titulo_cadastrar_produto.setStyleSheet("font: 16pt \"Montserrat\";\n"
"color: #9f3ffa;\n"
"")
        self.lbl_titulo_cadastrar_produto.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_titulo_cadastrar_produto.setWordWrap(False)
        self.lbl_titulo_cadastrar_produto.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.lbl_titulo_cadastrar_produto.setObjectName("lbl_titulo_cadastrar_produto")
        self.tabela_cadastro = QtWidgets.QTableWidget(self.pg_cadastar_produtos)
        self.tabela_cadastro.setGeometry(QtCore.QRect(20, 200, 991, 351))
        self.tabela_cadastro.setStyleSheet("QTableWidget {\n"
"    gridline-color: #9f3ffa;;\n"
"    background-color: transparent;\n"
"    outline: 0;\n"
"    border: 1px solid #9f3ffa;\n"
"    border-top: 0px\n"
"    \n"
"}\n"
"\n"
"QTableWidget::item:selected{\n"
"    background-color:#9f3ffa;;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: #9f3ffa;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid #9f3ffa;\n"
"    background-color: transparent;\n"
"    border-left: 0px;\n"
"    color: black;\n"
"\n"
"}\n"
"")
        self.tabela_cadastro.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabela_cadastro.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tabela_cadastro.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tabela_cadastro.setTabKeyNavigation(True)
        self.tabela_cadastro.setProperty("showDropIndicator", False)
        self.tabela_cadastro.setAlternatingRowColors(False)
        self.tabela_cadastro.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tabela_cadastro.setGridStyle(QtCore.Qt.SolidLine)
        self.tabela_cadastro.setObjectName("tabela_cadastro")
        self.tabela_cadastro.setColumnCount(6)
        self.tabela_cadastro.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_cadastro.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_cadastro.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_cadastro.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_cadastro.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_cadastro.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_cadastro.setHorizontalHeaderItem(5, item)
        self.tabela_cadastro.verticalHeader().setVisible(False)
        self.tabela_cadastro.verticalHeader().setSortIndicatorShown(False)
        self.tabela_cadastro.verticalHeader().setStretchLastSection(False)
        self.line_codigo_produto_cadastrar = QtWidgets.QLineEdit(self.pg_cadastar_produtos)
        self.line_codigo_produto_cadastrar.setGeometry(QtCore.QRect(20, 90, 161, 31))
        self.line_codigo_produto_cadastrar.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_codigo_produto_cadastrar.setClearButtonEnabled(True)
        self.line_codigo_produto_cadastrar.setObjectName("line_codigo_produto_cadastrar")
        self.line_descricao_cadastrar = QtWidgets.QLineEdit(self.pg_cadastar_produtos)
        self.line_descricao_cadastrar.setGeometry(QtCore.QRect(200, 90, 161, 31))
        self.line_descricao_cadastrar.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_descricao_cadastrar.setClearButtonEnabled(True)
        self.line_descricao_cadastrar.setObjectName("line_descricao_cadastrar")
        self.line_valor_cadastrar = QtWidgets.QLineEdit(self.pg_cadastar_produtos)
        self.line_valor_cadastrar.setGeometry(QtCore.QRect(380, 90, 161, 31))
        self.line_valor_cadastrar.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_valor_cadastrar.setClearButtonEnabled(True)
        self.line_valor_cadastrar.setObjectName("line_valor_cadastrar")
        self.line_qtde_cadastrar = QtWidgets.QLineEdit(self.pg_cadastar_produtos)
        self.line_qtde_cadastrar.setGeometry(QtCore.QRect(20, 150, 161, 31))
        self.line_qtde_cadastrar.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_qtde_cadastrar.setClearButtonEnabled(True)
        self.line_qtde_cadastrar.setObjectName("line_qtde_cadastrar")
        self.line_fornecedor_cadastrar = QtWidgets.QLineEdit(self.pg_cadastar_produtos)
        self.line_fornecedor_cadastrar.setGeometry(QtCore.QRect(200, 150, 161, 31))
        self.line_fornecedor_cadastrar.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_fornecedor_cadastrar.setClearButtonEnabled(True)
        self.line_fornecedor_cadastrar.setObjectName("line_fornecedor_cadastrar")
        self.btn_finalizar_cadastro = QtWidgets.QPushButton(self.pg_cadastar_produtos)
        self.btn_finalizar_cadastro.setGeometry(QtCore.QRect(380, 150, 161, 31))
        self.btn_finalizar_cadastro.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_finalizar_cadastro.setObjectName("btn_finalizar_cadastro")
        self.Telas_do_menu.addWidget(self.pg_cadastar_produtos)
        self.pg_alterar_produtos = QtWidgets.QWidget()
        self.pg_alterar_produtos.setObjectName("pg_alterar_produtos")
        self.btn_finalizar_alterar = QtWidgets.QPushButton(self.pg_alterar_produtos)
        self.btn_finalizar_alterar.setGeometry(QtCore.QRect(380, 140, 161, 31))
        self.btn_finalizar_alterar.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(159, 63, 250);\n"
"color: white;\n"
"border-radius: 5px;\n"
"font: 10pt \"Montserrat\";\n"
"outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 62, 255);\n"
"}\n"
"")
        self.btn_finalizar_alterar.setObjectName("btn_finalizar_alterar")
        self.line_fornecedor_alterar = QtWidgets.QLineEdit(self.pg_alterar_produtos)
        self.line_fornecedor_alterar.setGeometry(QtCore.QRect(200, 140, 161, 31))
        self.line_fornecedor_alterar.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_fornecedor_alterar.setClearButtonEnabled(True)
        self.line_fornecedor_alterar.setObjectName("line_fornecedor_alterar")
        self.tabela_alterar = QtWidgets.QTableWidget(self.pg_alterar_produtos)
        self.tabela_alterar.setGeometry(QtCore.QRect(20, 190, 991, 351))
        self.tabela_alterar.setStyleSheet("QTableWidget {\n"
"    gridline-color: #9f3ffa;;\n"
"    background-color: transparent;\n"
"    outline: 0;\n"
"    border: 1px solid #9f3ffa;\n"
"    border-top: 0px\n"
"    \n"
"}\n"
"\n"
"QTableWidget::item:selected{\n"
"    background-color:#9f3ffa;;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: #9f3ffa;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid #9f3ffa;\n"
"    background-color: transparent;\n"
"    border-left: 0px;\n"
"    color: black;\n"
"\n"
"}\n"
"")
        self.tabela_alterar.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabela_alterar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tabela_alterar.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tabela_alterar.setTabKeyNavigation(True)
        self.tabela_alterar.setProperty("showDropIndicator", False)
        self.tabela_alterar.setAlternatingRowColors(False)
        self.tabela_alterar.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tabela_alterar.setGridStyle(QtCore.Qt.SolidLine)
        self.tabela_alterar.setObjectName("tabela_alterar")
        self.tabela_alterar.setColumnCount(6)
        self.tabela_alterar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_alterar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_alterar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_alterar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_alterar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_alterar.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_alterar.setHorizontalHeaderItem(5, item)
        self.tabela_alterar.verticalHeader().setVisible(False)
        self.tabela_alterar.verticalHeader().setSortIndicatorShown(False)
        self.tabela_alterar.verticalHeader().setStretchLastSection(False)
        self.lbl_titulo_alterar = QtWidgets.QLabel(self.pg_alterar_produtos)
        self.lbl_titulo_alterar.setGeometry(QtCore.QRect(20, 20, 241, 41))
        self.lbl_titulo_alterar.setStyleSheet("font: 16pt \"Montserrat\";\n"
"color: #9f3ffa;\n"
"")
        self.lbl_titulo_alterar.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_titulo_alterar.setWordWrap(False)
        self.lbl_titulo_alterar.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.lbl_titulo_alterar.setObjectName("lbl_titulo_alterar")
        self.line_valor_alterar = QtWidgets.QLineEdit(self.pg_alterar_produtos)
        self.line_valor_alterar.setGeometry(QtCore.QRect(380, 80, 161, 31))
        self.line_valor_alterar.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_valor_alterar.setClearButtonEnabled(True)
        self.line_valor_alterar.setObjectName("line_valor_alterar")
        self.line_qtde_alterar = QtWidgets.QLineEdit(self.pg_alterar_produtos)
        self.line_qtde_alterar.setGeometry(QtCore.QRect(20, 140, 161, 31))
        self.line_qtde_alterar.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_qtde_alterar.setClearButtonEnabled(True)
        self.line_qtde_alterar.setObjectName("line_qtde_alterar")
        self.line_codigo_alterar = QtWidgets.QLineEdit(self.pg_alterar_produtos)
        self.line_codigo_alterar.setGeometry(QtCore.QRect(20, 80, 161, 31))
        self.line_codigo_alterar.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_codigo_alterar.setClearButtonEnabled(True)
        self.line_codigo_alterar.setObjectName("line_codigo_alterar")
        self.line_decricao_alterar = QtWidgets.QLineEdit(self.pg_alterar_produtos)
        self.line_decricao_alterar.setGeometry(QtCore.QRect(200, 80, 161, 31))
        self.line_decricao_alterar.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(159, 63, 250);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_decricao_alterar.setClearButtonEnabled(True)
        self.line_decricao_alterar.setObjectName("line_decricao_alterar")
        self.Telas_do_menu.addWidget(self.pg_alterar_produtos)
        self.TelasPrincipais.addWidget(self.Admin)
        self.Colaborador = QtWidgets.QWidget()
        self.Colaborador.setObjectName("Colaborador")
        self.TelasPrincipais.addWidget(self.Colaborador)
        FrmAdmin.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmAdmin)
        self.TelasPrincipais.setCurrentIndex(0)
        self.Telas_do_menu.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(FrmAdmin)

    def retranslateUi(self, FrmAdmin):
        _translate = QtCore.QCoreApplication.translate
        FrmAdmin.setWindowTitle(_translate("FrmAdmin", "PyStock"))
        self.lbl_seja_bem_vindo.setText(_translate("FrmAdmin", "Seja bem-vindo(a)"))
        self.lbl_titulo.setText(_translate("FrmAdmin", "Últimas Notícias"))
        self.lbl_noticia3.setText(_translate("FrmAdmin", "Tem alguma sugestão do que podemos melhorar?\n"
"Se sim, deixe sua sugestão com o rh."))
        self.lbl_noticia1.setText(_translate("FrmAdmin", "Não recebeu seu passe? Entre em contato com o rh\n"
"via e-mail ou faça um chamado."))
        self.lbl_noticia2.setText(_translate("FrmAdmin", "Use a vontade nossos ambientes de descontração!"))
        self.label_3.setText(_translate("FrmAdmin", "PyStock - A melhor forma\n"
"de gerenciar estoque!"))
        self.lbl_titulo_fornecedores.setText(_translate("FrmAdmin", "Fornecedores Cadastrados"))
        self.btn_editar_fornecedores.setText(_translate("FrmAdmin", "Editar"))
        self.btn_excluir_fornecedores.setText(_translate("FrmAdmin", "Excluir"))
        self.tabela_fornecedores.setSortingEnabled(True)
        item = self.tabela_fornecedores.horizontalHeaderItem(0)
        item.setText(_translate("FrmAdmin", "Fornecedor"))
        item = self.tabela_fornecedores.horizontalHeaderItem(1)
        item.setText(_translate("FrmAdmin", "Endereço"))
        item = self.tabela_fornecedores.horizontalHeaderItem(2)
        item.setText(_translate("FrmAdmin", "Contato"))
        self.btn_adicionar_forncedores.setText(_translate("FrmAdmin", "Adicionar"))
        self.lbl_titulo_colaboradores.setText(_translate("FrmAdmin", "Cadastro de Colaboradores"))
        self.radio_admin.setText(_translate("FrmAdmin", "Admin"))
        self.radio_colaborador.setText(_translate("FrmAdmin", "Colaborador"))
        self.line_nome.setPlaceholderText(_translate("FrmAdmin", "Nome Completo"))
        self.line_login.setPlaceholderText(_translate("FrmAdmin", "Login"))
        self.line_senha.setPlaceholderText(_translate("FrmAdmin", "Senha"))
        self.btn_cadastro.setText(_translate("FrmAdmin", "Efetuar Cadastro"))
        self.lbl_titulo_usuario_vendas.setText(_translate("FrmAdmin", "Vendedor - Usuário"))
        self.line_cliente.setPlaceholderText(_translate("FrmAdmin", "Cliente"))
        self.tabela_vendas.setSortingEnabled(True)
        item = self.tabela_vendas.horizontalHeaderItem(0)
        item.setText(_translate("FrmAdmin", "Item"))
        item = self.tabela_vendas.horizontalHeaderItem(1)
        item.setText(_translate("FrmAdmin", "Cód"))
        item = self.tabela_vendas.horizontalHeaderItem(2)
        item.setText(_translate("FrmAdmin", "Produto"))
        item = self.tabela_vendas.horizontalHeaderItem(3)
        item.setText(_translate("FrmAdmin", "Valor Unitário"))
        item = self.tabela_vendas.horizontalHeaderItem(4)
        item.setText(_translate("FrmAdmin", "Qtde."))
        item = self.tabela_vendas.horizontalHeaderItem(5)
        item.setText(_translate("FrmAdmin", "Total"))
        self.line_codigo_vendas.setPlaceholderText(_translate("FrmAdmin", "Cód produto"))
        self.line_quantidade_vendas.setPlaceholderText(_translate("FrmAdmin", "Quantidade"))
        self.line_search_bar.setPlaceholderText(_translate("FrmAdmin", "Buscar Produtos"))
        self.lbl_total_venda.setText(_translate("FrmAdmin", "Total da Venda:  R$"))
        self.lbl_total_valor.setText(_translate("FrmAdmin", "0,00"))
        self.line_desconto_vendas.setPlaceholderText(_translate("FrmAdmin", "Desconto"))
        self.btn_adicionar_compra.setText(_translate("FrmAdmin", "Adicionar"))
        self.btn_excluir_item.setText(_translate("FrmAdmin", "Excluir Item"))
        self.btn_finalizar_compra.setText(_translate("FrmAdmin", "Finalizar Compra"))
        self.btn_confirmar_cliente.setText(_translate("FrmAdmin", "Confirmar"))
        self.btn_pagamento.setText(_translate("FrmAdmin", "Pagamento"))
        self.lbl_hora_data.setText(_translate("FrmAdmin", "00:00 00/00/0000"))
        self.lbl_titulo_produtos.setText(_translate("FrmAdmin", "Produtos Cadastrados"))
        self.tabela_produto.setSortingEnabled(True)
        item = self.tabela_produto.horizontalHeaderItem(0)
        item.setText(_translate("FrmAdmin", "Item"))
        item = self.tabela_produto.horizontalHeaderItem(1)
        item.setText(_translate("FrmAdmin", "Cód"))
        item = self.tabela_produto.horizontalHeaderItem(2)
        item.setText(_translate("FrmAdmin", "Produto"))
        item = self.tabela_produto.horizontalHeaderItem(3)
        item.setText(_translate("FrmAdmin", "Valor Unitário"))
        item = self.tabela_produto.horizontalHeaderItem(4)
        item.setText(_translate("FrmAdmin", "Qtde."))
        item = self.tabela_produto.horizontalHeaderItem(5)
        item.setText(_translate("FrmAdmin", "Fornecedor"))
        self.btn_cadastrar_produto.setText(_translate("FrmAdmin", "Cadastrar"))
        self.btn_alterar_produto.setText(_translate("FrmAdmin", "Alterar"))
        self.btn_excluir_produto.setText(_translate("FrmAdmin", "Excluir"))
        self.line_search_Bar.setPlaceholderText(_translate("FrmAdmin", "Filtrar Produtos"))
        self.line_codigo_produto.setPlaceholderText(_translate("FrmAdmin", "Cód produto"))
        self.btn_confirmar_codigo.setText(_translate("FrmAdmin", "Confirmar"))
        self.lbl_hora_data_produtos.setText(_translate("FrmAdmin", "00:00 00/00/0000"))
        self.lbl_titulo_cadastrar_produto.setText(_translate("FrmAdmin", "Cadastrar Produtos"))
        self.tabela_cadastro.setSortingEnabled(True)
        item = self.tabela_cadastro.horizontalHeaderItem(0)
        item.setText(_translate("FrmAdmin", "Item"))
        item = self.tabela_cadastro.horizontalHeaderItem(1)
        item.setText(_translate("FrmAdmin", "Cód"))
        item = self.tabela_cadastro.horizontalHeaderItem(2)
        item.setText(_translate("FrmAdmin", "Produto"))
        item = self.tabela_cadastro.horizontalHeaderItem(3)
        item.setText(_translate("FrmAdmin", "Valor Unitário"))
        item = self.tabela_cadastro.horizontalHeaderItem(4)
        item.setText(_translate("FrmAdmin", "Qtde."))
        item = self.tabela_cadastro.horizontalHeaderItem(5)
        item.setText(_translate("FrmAdmin", "Fornecedor"))
        self.line_codigo_produto_cadastrar.setPlaceholderText(_translate("FrmAdmin", "Cód produto"))
        self.line_descricao_cadastrar.setPlaceholderText(_translate("FrmAdmin", "Descrição"))
        self.line_valor_cadastrar.setPlaceholderText(_translate("FrmAdmin", "Valor Unitário"))
        self.line_qtde_cadastrar.setPlaceholderText(_translate("FrmAdmin", "Quantidade Estoque"))
        self.line_fornecedor_cadastrar.setPlaceholderText(_translate("FrmAdmin", "Fornecedor"))
        self.btn_finalizar_cadastro.setText(_translate("FrmAdmin", "Finalizar Cadastro"))
        self.btn_finalizar_alterar.setText(_translate("FrmAdmin", "Finalizar Alteração"))
        self.line_fornecedor_alterar.setPlaceholderText(_translate("FrmAdmin", "Fornecedor"))
        self.tabela_alterar.setSortingEnabled(True)
        item = self.tabela_alterar.horizontalHeaderItem(0)
        item.setText(_translate("FrmAdmin", "Item"))
        item = self.tabela_alterar.horizontalHeaderItem(1)
        item.setText(_translate("FrmAdmin", "Cód"))
        item = self.tabela_alterar.horizontalHeaderItem(2)
        item.setText(_translate("FrmAdmin", "Produto"))
        item = self.tabela_alterar.horizontalHeaderItem(3)
        item.setText(_translate("FrmAdmin", "Valor Unitário"))
        item = self.tabela_alterar.horizontalHeaderItem(4)
        item.setText(_translate("FrmAdmin", "Qtde."))
        item = self.tabela_alterar.horizontalHeaderItem(5)
        item.setText(_translate("FrmAdmin", "Fornecedor"))
        self.lbl_titulo_alterar.setText(_translate("FrmAdmin", "Alterar Produtos"))
        self.line_valor_alterar.setPlaceholderText(_translate("FrmAdmin", "Valor Unitário"))
        self.line_qtde_alterar.setPlaceholderText(_translate("FrmAdmin", "Quantidade Estoque"))
        self.line_codigo_alterar.setPlaceholderText(_translate("FrmAdmin", "Cód produto"))
        self.line_decricao_alterar.setPlaceholderText(_translate("FrmAdmin", "Descrição"))
from View.PY import file_principal_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmAdmin = QtWidgets.QMainWindow()
    ui = Ui_FrmColaborador()
    ui.setupUi(FrmAdmin)
    FrmAdmin.show()
    sys.exit(app.exec_())
