# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 611)
        MainWindow.setMinimumSize(QtCore.QSize(1091, 611))
        MainWindow.setMaximumSize(QtCore.QSize(1091, 611))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TelasPrincipais = QtWidgets.QStackedWidget(self.centralwidget)
        self.TelasPrincipais.setGeometry(QtCore.QRect(0, 0, 1091, 611))
        self.TelasPrincipais.setMinimumSize(QtCore.QSize(1091, 611))
        self.TelasPrincipais.setMaximumSize(QtCore.QSize(1091, 611))
        self.TelasPrincipais.setObjectName("TelasPrincipais")
        self.Admin = QtWidgets.QWidget()
        self.Admin.setObjectName("Admin")
        self.frame = QtWidgets.QFrame(self.Admin)
        self.frame.setGeometry(QtCore.QRect(0, 0, 61, 611))
        self.frame.setStyleSheet("background-color: rgb(159, 63, 250);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.pushButton.setStyleSheet("QPushButton {\n"
"border: solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: solid;\n"
"    background-color: rgb(159, 103, 250);\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icones/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(self.Admin)
        self.frame_2.setGeometry(QtCore.QRect(60, 0, 1041, 51))
        self.frame_2.setStyleSheet("background-color: rgb(159, 63, 250);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(910, 0, 61, 51))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"border: solid;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: solid;\n"
"    background-color: rgb(159, 103, 250);\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icones/Emoji-Seta-PNG-1024x1024.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(970, 0, 61, 51))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"border: solid;\n"
"font: 18pt \"Montserrat\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 17, 49);\n"
"\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.Admin)
        self.label.setGeometry(QtCore.QRect(330, 90, 471, 461))
        self.label.setStyleSheet("background-image: url(:/icones/logo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.TelasPrincipais.addWidget(self.Admin)
        self.Colaborador = QtWidgets.QWidget()
        self.Colaborador.setObjectName("Colaborador")
        self.TelasPrincipais.addWidget(self.Colaborador)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyStock"))
        self.pushButton_3.setText(_translate("MainWindow", "X"))

from View.PY import file_principal_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())